// Generated by CoffeeScript 1.7.1
(function() {
  var indexCtrl, parseList, parsePost, parseTitle, postCtrl;

  window.myblogApp = angular.module('myblog', ["ngRoute", "ngAnimate"]);

  myblogApp.config(function($routeProvider, $locationProvider) {
    var list;
    list = "<div class=\"main-bar\">" + "<div  ng-repeat=\"post in blogList | blogListType : type\" class=\"md\">" + "<div class=\"date\">" + "<p class=\"month\">{{post.date.month}}月</p>" + "<p class=\"day\">{{post.date.day}}</p>" + "</div>" + "<div class=\"md-context\">" + "<h1>{{post.title}}</h1>" + "<div class=\"shot-text\">" + "<p>{{post.disc}}</p>" + "</div>" + "</div>" + "<div class=\"md-foot\">" + "<a ng-click=\"Scroll2Top()\" ng-href=\"#/post/{{post.url}}\"><button class=\"pull-right btn btn-danger\">阅读全文</button></a>" + "</div>" + "</div>" + "</div>";
    return $routeProvider.when("/", {
      template: list
    }).when("/type/:type", {
      template: list
    }).when("/post/:name", {
      templateUrl: "partials/page.html"
    }).otherwise({
      redirectTo: "/"
    });
  });

  myblogApp.filter('blogListType', function() {
    var blogListType;
    return blogListType = function(date, array) {
      var i, output, type, _i, _len;
      type = array.type;
      if (type) {
        output = {};
        for (_i = 0, _len = date.length; _i < _len; _i++) {
          i = date[_i];
          if (i.type === type) {
            output[_i] = i;
          }
        }
        return output;
      }
      return date;
    };
  });

  myblogApp.directive('markdown', function() {
    return {
      restrict: 'EA',
      scope: {
        content: '=markdownContent'
      },
      link: function(scope, element, attrs) {
        return scope.$watch((function() {
          return scope.content;
        }), function(newValue) {
          element.html(marked(newValue ? newValue : "#loading..."));
          return element.find('pre>code').each(function(i, block) {
            return hljs.highlightBlock(block);
          });
        });
      }
    };
  });

  myblogApp.directive('markdownlist', function() {
    return {
      restrict: 'EA',
      link: function(scope, element, attrs) {
        return element.html(marked(element.text()));
      }
    };
  });

  parseTitle = function(data) {
    var key, line, r, value, _i, _len, _ref, _ref1;
    r = {
      title: "",
      type: "",
      tag: "",
      disc: "",
      url: "",
      hide: ""
    };
    _ref = data.split('\n');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      line = _ref[_i];
      _ref1 = line.split(':'), key = _ref1[0], value = _ref1[1];
      key = _.str.trim(key);
      value = _.str.trim(value);
      if (r.hasOwnProperty(key)) {
        r[key] = value;
      }
    }
    r.date = r.url.split('-');
    r.date.month = parseInt(r.date[1], 10);
    r.date.day = parseInt(r.date[2], 10);
    return r;
  };

  parseList = function(data) {
    return _.map(data.split(/\n[\-=]+/), parseTitle);
  };

  parsePost = function(text) {
    var flag, head, line, post, tail, _i, _len, _ref;
    flag = false;
    head = "";
    tail = "";
    _ref = text.split('\n');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      line = _ref[_i];
      if (/[\-=]+/.test(line)) {
        flag = true;
      }
      if (flag) {
        tail += '\n' + line;
      } else {
        head += '\n' + line + '\n';
      }
    }
    post = parseTitle(head);
    post.text = tail;
    if (post.hide === 'true') {
      return;
    }
    return post;
  };

  postCtrl = function($scope, $http, $routeParams) {
    var toggleDuoshuoComments;
    $scope.name = $routeParams.name;
    $http.get('post/' + $scope.name).success(function(data) {
      $scope.post = parsePost(data);
      return toggleDuoshuoComments('.blog-container');
    });
    return toggleDuoshuoComments = function(container) {
      var el;
      el = document.createElement('div');
      el.setAttribute('id', $scope.name);
      el.setAttribute('data-thread-key', $scope.post.title);
      el.setAttribute('data-url', $scope.name);
      DUOSHUO.EmbedThread(el);
      return jQuery(container).append(el);
    };
  };

  postCtrl.$inject = ['$scope', '$http', '$routeParams'];

  indexCtrl = function($scope, $http, $routeParams) {
    $scope.type = $routeParams;
    window.w = $scope;
    $http.get("post/list.md").success(function(data) {
      console.log('indexCtrl');
      $scope.blogList = _.filter(parseList(data), function(it) {
        return it.hide !== 'true';
      });
      return $scope.listType = _.uniq(_.pluck($scope.blogList, 'type'));
    });
    $scope.Scroll2Top = function() {
      return window.scrollTo(0, $(window).height() * 1.4);
    };
    return $('#fix-height').css('min-height', $(window).height());
  };

  indexCtrl.$inject = ['$scope', '$http', '$routeParams'];

  myblogApp.controller('postCtrl', postCtrl);

  myblogApp.controller('indexCtrl', indexCtrl);

}).call(this);

//# sourceMappingURL=controller.map
